# Generated by Django 4.2.9 on 2024-02-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('9am-10am', '9am-10am'), ('10am-11am', '10am-11am'), ('11am-12pm', '11am-12pm'), ('1pm-2pm', '1pm-2pm'), ('2pm-3pm', '2pm-3pm'), ('3pm-4pm', '3pm-4pm'), ('4pm-5pm', '4pm-5pm')], max_length=10),
        ),
    ]
